export default {};

export const ACTIONS = {
  APP: {
    START: 'APP-START',
    STARTED: 'APP-STARTED',
    FATAL: 'APP-FATAL',
  },
  USERS: {
    RESET: 'USERS-RESET',
  },
  USERSCATEGORIES: {
    RESET: 'USERSCATEGORIES-RESET',
  },
  SPACE: {
    UPDATE: 'SPACE-UPDATE',
  },
  SPACEROOMS: {
    RESET: 'SPACEROOMS-RESET',
    AVAILABILITY: 'SPACEROOMS-AVAILABILITY',
  },
  ROOMSUSERS: {
    RESET: 'ROOMSUSERS-RESET',
  },
  ROOMSMSGS: {
    ADD: 'ROOMSMSGS-ADD',
    MERGE: 'ROOMSMSGS-MERGE',
  },
  CON: {
    ADD: 'CON-ADD',
    REMOVE: 'CON-REMOVE',
    MERGE: 'CON-MERGE',
  },
};
