export default {};

export const ACTIONS = {

  // App
  APP_START: 'APP_START',
  APP_STARTED: 'APP_STARTED',
  APP_ERROR: 'APP_ERROR',
  APP_FATAL: 'APP_FATAL',

  // Users
  USERS_RESET: 'USERS_RESET',

  // Users categories
  USERSCATEGORIES_RESET: 'USERSCATEGORIES_RESET',

  // Space
  SPACE_UPDATE: 'SPACE_UPDATE',

  // Space rooms
  SPACEROOMS_RESET: 'SPACEROOMS_RESET',
  SPACEROOMS_AVAILABILITY: 'SPACEROOMS_AVAILABILITY',

  // Rooms users
  ROOMSUSERS_RESET: 'ROOMSUSERS_RESET',

  // Rooms messages
  ROOMSMSGS_ADD: 'ROOMSMSGS_ADD',
  ROOMSMSGS_MERGE: 'ROOMSMSGS_MERGE',

  // Connections
  CON_ADD: 'CON_ADD',
  CON_REMOVE: 'CON_REMOVE',
  CON_MERGE: 'CON_MERGE',
};

export const DESIGN = {
  PRIMARY_COLOR: '#68b83f'
};
